### ISSUE TITLE
Error while map(), may I ask the version of packages?

### ISSUE THREAD

**Issue by BILLAAA** [townpeterson/vespa#1]
I tried to run the code, and it's absolutely useful to me, but while run map() it shows:

> map()
Error in as_mapper(.f, ...) : **Missing parameter ".f", no default value** _This is a translated version of error_

The version of R is 4.0.2 at first and I install the 3.6.2 as you referred to in your paper, but it failed to install a lot of packages now due to the requirements of a higher version of R. Could you please share the package version that has no conflict? Many thanks!!!

**Comment by marlonecobos** [comment]
Hi, please make sure the package "maps" is installed and loaded. That part of the code plots a map of the world. If the problem persists, try 

maps::map()

I hope it helps.

**Comment by BILLAAA** [comment]
Thank you so much, it works now. 👍 👍 👍 

wrld <- readOGR("WORLD","country")
Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv,  : 
  Cannot open data source

I do download the *.shp file and remove the postfix and put it in the WORLD folder. But it still doesn't work. :(
I've been searching this on the Internet for a while but still no solution.
Thank you in advance!

**Comment by BILLAAA** [comment]
> Thank you so much, it works now. 👍 👍 👍
> 
> wrld <- readOGR("WORLD","country")
> Error in ogrInfo(dsn = dsn, layer = layer, encoding = encoding, use_iconv = use_iconv, :
> Cannot open data source
> 
> I do download the *.shp file and remove the postfix and put it in the WORLD folder. But it still doesn't work. :(
> I've been searching this on the Internet for a while but still no solution.
> Thank you in advance!

Fix by redownloading the shp file, thanks!

**Comment by BILLAAA** [comment]
Hi @marlonecobos, thanks for your help, may I ask you why this happened?

unable to find an inherited method for function ‘coordinates<-’ for signature ‘"occdat"’

when running
